-- ==========================================
-- SUPABASE DATABASE SCHEMA FOR AGREEMENT SYSTEM
-- ==========================================
-- Run this SQL in your Supabase SQL Editor
-- Go to: Supabase Dashboard → SQL Editor → New Query → Paste this → Run

-- 1. Create Templates Table
CREATE TABLE IF NOT EXISTS templates (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  file_data BYTEA NOT NULL,
  placeholders TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  created_by TEXT
);

-- 2. Create Form Fields Table
CREATE TABLE IF NOT EXISTS form_fields (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('text', 'date', 'number', 'file')),
  created_at TIMESTAMP DEFAULT NOW()
);

-- 3. Create Form Configs Table
CREATE TABLE IF NOT EXISTS form_configs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  template_id BIGINT NOT NULL,
  fields JSONB NOT NULL DEFAULT '[]',
  mappings JSONB NOT NULL DEFAULT '[]',
  signature_pdf_data BYTEA,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  FOREIGN KEY (template_id) REFERENCES templates(id) ON DELETE CASCADE
);

-- 4. Create Generated Documents Table
CREATE TABLE IF NOT EXISTS generated_documents (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  date TIMESTAMP DEFAULT NOW(),
  size BIGINT,
  file_data BYTEA NOT NULL,
  mime_type TEXT DEFAULT 'application/pdf',
  extension TEXT DEFAULT 'pdf',
  template_id BIGINT,
  config_id BIGINT,
  form_data JSONB DEFAULT '{}',
  uploaded_appendages JSONB DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW(),
  FOREIGN KEY (template_id) REFERENCES templates(id) ON DELETE SET NULL,
  FOREIGN KEY (config_id) REFERENCES form_configs(id) ON DELETE SET NULL
);

-- 5. Create Indexes for faster queries
CREATE INDEX idx_templates_name ON templates(name);
CREATE INDEX idx_form_configs_template_id ON form_configs(template_id);
CREATE INDEX idx_generated_documents_template_id ON generated_documents(template_id);
CREATE INDEX idx_generated_documents_created_at ON generated_documents(created_at);

-- ==========================================
-- ENABLE ROW LEVEL SECURITY (Optional but Recommended)
-- ==========================================

ALTER TABLE templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE generated_documents ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read templates
CREATE POLICY "Anyone can read templates" ON templates
  FOR SELECT TO anon, authenticated
  USING (true);

-- Allow authenticated users to create/update templates
CREATE POLICY "Authenticated users can manage templates" ON templates
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);

-- Similar policies for form_configs and generated_documents
CREATE POLICY "Anyone can read form_configs" ON form_configs
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "Authenticated users can manage form_configs" ON form_configs
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Anyone can read generated_documents" ON generated_documents
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "Authenticated users can manage generated_documents" ON generated_documents
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);
